### ISSUE TITLE
Create use case for registration new company

### ISSUE THREAD

**Issue by DemiusAcademius** [04tudor/loyalty-campaign-service#16]
First of all, lets complete previous tasks!

use cases will be in application module
each use case is a separate interface, service what implements it, and command

example (from existing project)

```java
public interface RegistrationCampaignUseCase {

    Either<UseCaseProblemConflict, CampaignId> registerCampaign(RegisterCampaign command);

    static RegistrationCampaignUseCase defaultService(Campaigns campaigns) {
        return new RegistrationCampaignService(campaigns);
    }
}
```

**Comment by DemiusAcademius** [comment]
example of implementation
this is from existing project and must be revorked!

```java
package md.maib.retail.loyalty.campaign.application.manage;

import am.ik.yavi.builder.ValidatorBuilder;
import am.ik.yavi.core.ConstraintViolations;
import am.ik.yavi.core.Validator;
import io.vavr.control.Either;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.ToString;
import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignTag;

import java.time.LocalDate;
import java.util.List;

import static io.vavr.control.Either.left;
import static io.vavr.control.Either.right;

@Getter
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
@ToString
public final class RegisterCampaign {

    private final String name;
    private final LocalDate startInclusive;
    private final LocalDate endExclusive;
    private final List<CampaignTag> tags;
    private final List<CampaignRule> rules;

    private boolean validateRange() {
        if (startInclusive == null || endExclusive == null) {
            return true;
        }
        return startInclusive.isBefore(endExclusive);
    }

    private static final Validator<RegisterCampaign> validator = ValidatorBuilder
            .<RegisterCampaign>of()
            .constraint(RegisterCampaign::name, "name", c -> c.notBlank().message("must not be blank"))
            .constraint(RegisterCampaign::startInclusive, "startInclusive", c -> c.notNull().message("must not be null"))
            .constraint(RegisterCampaign::endExclusive, "endExclusive", c -> c.notNull().message("must not be null"))
            .constraintOnTarget(RegisterCampaign::validateRange,
                    "startInclusive",
                    "startInclusive.isBeforeEndExclusive",
                    "\"startInclusive\" must be before \"endExclusive\"")
            ._object(RegisterCampaign::tags, "tags", c -> c.notNull().message("must not be null"))
            .forEach(RegisterCampaign::rules, "rules", CampaignRule.validator)
            .build();

    public static Either<ConstraintViolations, RegisterCampaign> create(String name, LocalDate startInclusive, LocalDate endExclusive, List<CampaignTag> tags, List<CampaignRule> rules) {
        var command = new RegisterCampaign(name, startInclusive, endExclusive, tags, rules);
        var violations = validator.validate(command);
        return violations.isValid() ? right(command) : left(violations);
    }
}
 
```

**Comment by DemiusAcademius** [comment]
for validation we use yavi library, not a hibernate validation (https://yavi.ik.am/)
also we use vavr library for Either implementation

**Comment by DemiusAcademius** [comment]
Either and Optional are from functional programming (see https://www.haskell.org/ or Ocaml)
also functional programming exists in Rust, Scala, Kotlin and ... java

**Comment by DemiusAcademius** [comment]
example of implementation

```java
package md.maib.retail.loyalty.campaign.application.manage;

import io.vavr.control.Either;
import lombok.RequiredArgsConstructor;
import md.maib.commons.use.cases.problems.UseCaseProblemConflict;
import md.maib.retail.loyalty.campaign.domain.model.common.CampaignId;
import md.maib.retail.loyalty.campaign.domain.model.common.CampaignName;
import md.maib.retail.loyalty.campaign.domain.model.common.CampaignSponsor;
import md.maib.retail.loyalty.campaign.domain.model.common.ConditionOperator;
import md.maib.retail.loyalty.campaign.domain.model.common.PurchaseField;
import md.maib.retail.loyalty.campaign.domain.model.common.RuleId;
import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignEntities;
import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignEntity;
import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignTags;
import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignTagsList;
import md.maib.retail.loyalty.campaign.domain.model.manage.CashbackEffectEntity;
import md.maib.retail.loyalty.campaign.domain.model.manage.ConditionEntity;
import md.maib.retail.loyalty.campaign.domain.model.manage.ConditionId;
import md.maib.retail.loyalty.campaign.domain.model.manage.EffectId;
import md.maib.retail.loyalty.campaign.domain.model.manage.RuleEntity;
import org.threeten.extra.Interval;

import java.time.Instant;
import java.time.ZoneOffset;

import static io.vavr.control.Either.left;
import static io.vavr.control.Either.right;

@RequiredArgsConstructor
final class RegistrationCampaignService implements RegistrationCampaignUseCase {

    private final CampaignEntities campaigns;
    private final CampaignTags campaignTags;

    @Override
    public Either<UseCaseProblemConflict, CampaignId> registerCampaign(RegisterCampaign command) {
        var id = CampaignId.newIdentity();
        var name = new CampaignName(command.name());
        var startInclusive = command.startInclusive().atStartOfDay(ZoneOffset.UTC).toInstant();
        var endExclusive = command.endExclusive().atStartOfDay(ZoneOffset.UTC).toInstant();
        var interval = Interval.of(startInclusive, endExclusive);

        var rules = command.rules().stream()
                .map(rule -> {
                    var sponsor = CampaignSponsor.valueOf(rule.effect().sponsor());
                    var conditions = rule.conditions().stream()
                            .map(condition -> {
                                var field = PurchaseField.valueOf(condition.fieldName());
                                var operator = ConditionOperator.valueOf(condition.operator());
                                return new ConditionEntity(
                                        ConditionId.newIdentity(),
                                        condition.negated(),
                                        field,
                                        operator,
                                        condition.operatorModifier(),
                                        condition.value()
                                );
                            })
                            .toList();
                    return new RuleEntity(RuleId.newIdentity(), conditions, new CashbackEffectEntity(EffectId.newIdentity(), sponsor, rule.effect().rate()));
                })
                .toList();

        var campaign = new CampaignEntity(id, name, interval, rules, Instant.now());

        if (campaigns.create(campaign)) {
            if (!command.tags().isEmpty()) {
                var tags = new CampaignTagsList(id, command.tags());
                campaignTags.add(tags);
            }
            return right(id);
        }
        return left(new UseCaseProblemConflict("CampaignWithSameNameAlreadyExists"));
    }
}

```

**Comment by 04tudor** [comment]
> example of implementation this is from existing project and must be revorked!
> 
> ```java
> package md.maib.retail.loyalty.campaign.application.manage;
> 
> import am.ik.yavi.builder.ValidatorBuilder;
> import am.ik.yavi.core.ConstraintViolations;
> import am.ik.yavi.core.Validator;
> import io.vavr.control.Either;
> import lombok.AccessLevel;
> import lombok.Getter;
> import lombok.RequiredArgsConstructor;
> import lombok.ToString;
> import md.maib.retail.loyalty.campaign.domain.model.manage.CampaignTag;
> 
> import java.time.LocalDate;
> import java.util.List;
> 
> import static io.vavr.control.Either.left;
> import static io.vavr.control.Either.right;
> 
> @Getter
> @RequiredArgsConstructor(access = AccessLevel.PRIVATE)
> @ToString
> public final class RegisterCampaign {
> 
>     private final String name;
>     private final LocalDate startInclusive;
>     private final LocalDate endExclusive;
>     private final List<CampaignTag> tags;
>     private final List<CampaignRule> rules;
> 
>     private boolean validateRange() {
>         if (startInclusive == null || endExclusive == null) {
>             return true;
>         }
>         return startInclusive.isBefore(endExclusive);
>     }
> 
>     private static final Validator<RegisterCampaign> validator = ValidatorBuilder
>             .<RegisterCampaign>of()
>             .constraint(RegisterCampaign::name, "name", c -> c.notBlank().message("must not be blank"))
>             .constraint(RegisterCampaign::startInclusive, "startInclusive", c -> c.notNull().message("must not be null"))
>             .constraint(RegisterCampaign::endExclusive, "endExclusive", c -> c.notNull().message("must not be null"))
>             .constraintOnTarget(RegisterCampaign::validateRange,
>                     "startInclusive",
>                     "startInclusive.isBeforeEndExclusive",
>                     "\"startInclusive\" must be before \"endExclusive\"")
>             ._object(RegisterCampaign::tags, "tags", c -> c.notNull().message("must not be null"))
>             .forEach(RegisterCampaign::rules, "rules", CampaignRule.validator)
>             .build();
> 
>     public static Either<ConstraintViolations, RegisterCampaign> create(String name, LocalDate startInclusive, LocalDate endExclusive, List<CampaignTag> tags, List<CampaignRule> rules) {
>         var command = new RegisterCampaign(name, startInclusive, endExclusive, tags, rules);
>         var violations = validator.validate(command);
>         return violations.isValid() ? right(command) : left(violations);
>     }
> }
>  
> ```

package md.maib.retail.manage;

import am.ik.yavi.builder.ValidatorBuilder;
import am.ik.yavi.core.ConstraintViolations;
import am.ik.yavi.core.Validator;
import am.ik.yavi.fn.Either;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.RequiredArgsConstructor;
import lombok.ToString;
import md.maib.retail.model.campaign.CampaignState;
import md.maib.retail.model.campaign.LoyaltyEventType;
import md.maib.retail.model.conditions.Rule;


import java.time.LocalDate;
import java.util.List;

import static am.ik.yavi.fn.Either.left;
import static am.ik.yavi.fn.Either.right;

@Getter
@RequiredArgsConstructor(access = AccessLevel.PUBLIC)
@ToString
public final class  RegisterCampaign {
    private final String name;
    private final LocalDate startInclusive;
    private final LocalDate endExclusive;
    private final CampaignState state;
    private final LoyaltyEventType loyaltyEventType;
    private final List<Rule> rules;

    private static final String BLANK = "must not be blank";
    private static final String NOTNULL = "must not be null";
    private static final String ACTIVE = "must  be ACTIVE";

    private boolean validateRange() {
        return startInclusive == null || endExclusive == null || startInclusive.isBefore(endExclusive);
    }

    private static final Validator<RegisterCampaign> validator = ValidatorBuilder
            .<RegisterCampaign>of()
            .constraint(RegisterCampaign::name, "name", c -> c.notBlank().message(BLANK))
            .**constraint**(RegisterCampaign::startInclusive, "startInclusive", c -> c.**notNull**().message(NOTNULL))
            .constraint(RegisterCampaign::endExclusive, "endExclusive", c -> c.**notNull**().message(NOTNULL))
            .constraintOnTarget(RegisterCampaign::validateRange,
                    "startInclusive",
                    "startInclusive.isBeforeEndExclusive",
                    "\"startInclusive\" must be before \"endExclusive\"")
            .constraint((RegisterCampaign rc) -> rc.state(), "state", c -> c.equals("Active").message(ACTIVE))
            .constraint(RegisterCampaign::loyaltyEventType,"loyaltyEventType",c -> c.notNull().message(NOTNULL))
            .forEach(RegisterCampaign::rules, "rules", Rule.validator())
            .build();

    public static Either<ConstraintViolations, RegisterCampaign> create(String name, LocalDate startInclusive, LocalDate endExclusive, CampaignState state, LoyaltyEventType loyaltyEventType, List<Rule> rules) {
        var command = new RegisterCampaign(name, startInclusive, endExclusive, state, loyaltyEventType, rules);
        var violations = validator.validate(command);
        return violations.isValid() ? right(command) : left(violations);
    }
}

i have a problem at .constraint ,and notNull function 
,Cannot resolve method 'constraint(<method reference>, String, <lambda expression>)'
No candidates found for method call c.notNull().

**Comment by DemiusAcademius** [comment]
RegisterCampaign::startInclusive and RegisterCampaign::endExclusive are getters generated with lombok.
See file lombok.config: 
             lombok.accessors.fluent = true

**Comment by 04tudor** [comment]
> RegisterCampaign::startInclusive and RegisterCampaign::endExclusive are getters generated with lombok. See file lombok.config: lombok.accessors.fluent = true

it was an error about version of dependency.
